### ISSUE TITLE
The check position is not exactly the same as my query pos

### ISSUE THREAD

**Issue by LiyanJi-code** [mutalyzer/mutalyzer2#529]
Hi,
I encountered a strange error when I submitted a batch query.
Here is an example of the error. 
NM_031276.2(TEX11):c.2042A>C	(variantchecker): A not found at position 2127, found G instead.

The TEX11 gene in coding position 2042 is base A at the reference strand, however, the Mutalyzer2 gives a base at position 2127.
![image](https://user-images.githubusercontent.com/10182907/145514021-2f467f66-3c9a-4c6b-9327-79089f3b4d46.png)

Thanks a lot.

**Comment by mihailefter** [comment]
@LiyanJi-code

Please note that `c.2042` corresponds to nucleotide `2127` relative to the `NM_031276.2` sequence start. For more information please check also the following [HGVS page](https://varnomen.hgvs.org/bg-material/numbering/).

**Comment by LiyanJi-code** [comment]
Many thanks

mihailefter ***@***.***> 于2021年12月10日周五 16:07写道：
